-- Script SQL base para fazer o select dos filtros
-- Esta query inclui todas as informações: motorista, veículo, status, etc.

SELECT
    CAB.NUMPEDIDO,
    CAB.NUMCARGA,
    CAB.CODCLIENTE,
    CLI.NOME AS CLIENTE,
    CLI.FANTASIA,
    CASE 
        WHEN SE.STATUS = 1 THEN 'SEPARADO'
        WHEN PROD_FALTANTES.QTD_FALTANTES > 0 THEN 'PENDENTE'
        ELSE 'PENDENTE'
    END AS STATUS_EXPEDICAO,
    CASE 
        WHEN SE.STATUS = 1 THEN 'F'
        ELSE 'B'
    END AS STATUS,
    CONVERT(CHAR(10), CAB.DTSAIDA, 120) AS DTSAIDA,
    CONVERT(CHAR(10), CAB.DTPREVENTREGA, 120) AS DTPREVENTREGA,
    CAB.CODVENDEDOR,
    V.NOME AS VENDEDOR,
    CAB.OBSERVACAO,
    CAB.OBSPEDIDO,
    CAB.CODTRANSPORTADORA,
    TRANSP.NOME AS NOMETRANSPORTADORA,
    CID.CIDADE AS NOME_CIDADE,
    CID.UF AS UF_CIDADE,
    ISNULL(VEIC.DESCRICAO, 'N/A') AS VEICULO,
    ISNULL(MOT.NOME, 'N/A') AS MOTORISTA,
    ISNULL(PROD_FALTANTES.QTD_FALTANTES, 0) AS QTD_PRODUTOS_FALTANTES,
    COALESCE(SE.STATUS, 0) AS STATUS_BIT
FROM CABPEDVENDA CAB WITH(NOLOCK)
INNER JOIN PESSOA CLI WITH(NOLOCK) ON CAB.CODCLIENTE = CLI.CODIGO
INNER JOIN VENDEDOR V WITH(NOLOCK) ON V.CODIGO = CAB.CODVENDEDOR
INNER JOIN CIDADE CID WITH(NOLOCK) ON CID.CODMUNICIPIO = CLI.CODCIDADE
LEFT JOIN PESSOA TRANSP WITH(NOLOCK) ON CAB.CODTRANSPORTADORA = TRANSP.CODIGO
LEFT JOIN CARREGAMENTO CAR WITH(NOLOCK) ON CAB.NUMCARGA = CAR.NUMCARGA
LEFT JOIN VEICULO VEIC WITH(NOLOCK) ON CAR.CODVEICULO = VEIC.CODIGO
LEFT JOIN PESSOA MOT WITH(NOLOCK) ON CAR.CODMOTORISTA = MOT.CODIGO
LEFT JOIN STATUS_EXPEDICAO SE WITH(NOLOCK) ON CAB.NUMPEDIDO = SE.NUMPEDIDO
LEFT JOIN (
    SELECT
        I.NUMPEDIDO,
        COUNT(CASE WHEN I.QTRESTANTE > 0 THEN 1 END) AS QTD_FALTANTES
    FROM ITEMPEDVENDA I WITH(NOLOCK)
    WHERE I.QTRESTANTE > 0
    GROUP BY I.NUMPEDIDO
) PROD_FALTANTES ON CAB.NUMPEDIDO = PROD_FALTANTES.NUMPEDIDO
WHERE CAB.STATUS = 'B'
AND CAB.ISFATURADO = 1
AND CAB.DTSAIDA LIKE '%2024-01-15%'  -- Substitua pela data desejada
ORDER BY CAB.DTSAIDA DESC;

-- Exemplos de filtros que podem ser adicionados:

-- Filtrar por cliente
-- AND CLI.CODIGO = 123

-- Filtrar por vendedor
-- AND CAB.CODVENDEDOR = 456

-- Filtrar por transportadora
-- AND CAB.CODTRANSPORTADORA = 789

-- Filtrar por número do pedido
-- AND CAB.NUMPEDIDO = 12345

-- Filtrar por número da carga
-- AND CAB.NUMCARGA = 67890

-- Filtrar por veículo
-- AND VEIC.CODIGO = 111

-- Filtrar por motorista
-- AND MOT.CODIGO = 222

-- Filtrar por status de expedição
-- AND SE.STATUS = 1  -- 1 = Separado, 0 = Pendente

-- Filtrar por produtos faltantes
-- AND PROD_FALTANTES.QTD_FALTANTES > 0 