exec sp_executesql N'SELECT CAB.CODEMPRESA, CAB.NUMPEDIDO, CAB.CODCLIENTE, CLI.NOME AS CLIENTE, CLI.FANTASIA, CAB.STATUS, ISNULL(CAB.NUMCARGA,0) AS NUMCARGA, ISNULL(CAB.NUMPEDIDOFV,0) AS NUMPEDIDOFV, 
(CONVERT( CHAR(10), CAB.DTEMISSAO, 120 ) + '' '' + CONVERT(VARCHAR(8), CAB.DTEMISSAO, 108)) AS DTEMISSAO, CLI.CNPJ, CAB.CODVENDEDOR, V.NOME AS VENDEDOR, 
CAB.CODCOBRANCA, ISNULL(PLANO.PLANO,'''') PLANO, NAT.DESCRICAO AS NATOPERACAO, CAB.MODELO, CAB.SERIE, CAB.TIPOVENDA, ISNULL(CAB.VLTOTNOTA,0) AS VLTOTNOTA, ISNULL(CAB.VLTOTITENS,0) AS VLTOTITENS, 
ISNULL(CAB.VLTOTENTREGUE,0) AS VLTOTENTREGUE, ISNULL(CAB.VLTOTRESTANTE,0) AS VLTOTRESTANTE, ISNULL(CAB.PERDESCVENDA,0) AS PERDESCVENDA, ISNULL(CAB.VLDESCVENDA,0) AS VLDESCVENDA, 
ISNULL(CAB.TOTPESOBRUTO,0) AS TOTPESOBRUTO, ISNULL(CAB.TOTPESOLIQUIDO,0) AS TOTPESOLIQUIDO, CAB.OBSERVACAO, CAB.OBSPEDIDO,  
ISNULL(CAB.CODFUNCLANC,0) AS CODFUNCLANC, FUNCLANC.NOME AS FUNCLANCAMENTO, ISNULL(CAB.CODFUNCCANC,0) AS CODFUNCCANC, FUNCCANC.NOME AS FUNCCANCELAMENTO,  
ISNULL(CAB.CODFUNCALTERACAO,0) AS CODFUNCALTERACAO, FUNCALT.NOME AS FUNCALTERACAO, ISNULL(CAB.CODFUNCLIB,0) AS CODFUNCLIB, FUNCLIB.NOME AS FUNCLIBERACAO, CAB.MOTIVOBLOQ, CAB.MOTIVOCANC, 
(CONVERT( CHAR(10), CAB.DTLIBERACAO, 120 ) + '' '' + CONVERT(VARCHAR(8), CAB.DTLIBERACAO, 108)) AS DTLIBERACAO, CAB.ISFATURADO, CONVERT( CHAR(10), CAB.DTPREVENTREGA, 120 ) AS DTPREVENTREGA, CPFNANOTA.NOME, 
ISNULL(NAT.CODIGO,0) AS CODNATOPERACAO, (CONVERT( CHAR(10), LOGFV.DTENVIO, 120 ) + '' '' + CONVERT(VARCHAR(8), LOGFV.DTENVIO, 108)) AS DTENVIO, ISNULL(CAB.VLFRETE,0) AS VLFRETE, 
CONVERT( CHAR(10), CAB.DTCANCELAMENTO, 120 ) AS DTCANCELAMENTO, ISNULL(LOGFV.UTILIZOUTROCA, 0) AS UTILIZOUTROCA, (CONVERT( CHAR(10), CAB.DTULTALTERACAO, 120 ) + '' '' + CONVERT(VARCHAR(8), CAB.DTULTALTERACAO, 108)) AS DTULTALTERACAO, 
ISNULL(CABC.NUMOP, 0) AS NUMOP, ISNULL(CABC.NUMPEDCOMPRA, 0) AS NUMPEDCOMPRA, CAB.TIPOFRETE, CID.CIDADE AS NOME_CIDADE, CID.UF AS UF_CIDADE, CLI.CODRAMOATIVIDADE, RAMO.DESCRICAO AS RAMOATIVIDADE, COB.DESCRICAO AS COBRANCA, 
CAB.CODTRANSPORTADORA, TRANSP.NOME AS NOMETRANSPORTADORA 
    FROM PESSOA CLI WITH(NOLOCK)  
    LEFT JOIN PESSOA_COMPLEMENTOS COMPCLI WITH(NOLOCK) ON (CLI.CODIGO = COMPCLI.CODPESSOA) 
    LEFT JOIN RAMOATIVIDADE RAMO WITH(NOLOCK) ON CLI.CODRAMOATIVIDADE = RAMO.ID, 
    CIDADE CID WITH(NOLOCK), REGIAO REG WITH(NOLOCK), VENDEDOR V WITH(NOLOCK), NATOPERACAO NAT WITH(NOLOCK), CABPEDVENDA CAB WITH(NOLOCK) 
    LEFT JOIN PESSOA FUNCLANC WITH(NOLOCK) ON (FUNCLANC.CODIGO = CAB.CODFUNCLANC) 
    LEFT JOIN PESSOA FUNCCANC WITH(NOLOCK) ON (FUNCCANC.CODIGO = CAB.CODFUNCCANC) 
    LEFT JOIN PESSOA FUNCALT WITH(NOLOCK) ON (FUNCALT.CODIGO = CAB.CODFUNCALTERACAO) 
    LEFT JOIN PESSOA FUNCLIB WITH(NOLOCK) ON (FUNCLIB.CODIGO = CAB.CODFUNCLIB) 
    LEFT JOIN CPFNANOTA CPFNANOTA WITH(NOLOCK) ON (CPFNANOTA.CODIGO = CAB.CODCPFNANOTA) 
    LEFT JOIN PLANOPGTO PLANO WITH(NOLOCK) ON (PLANO.CODIGO = CAB.CODPLANOPGTO) 
    LEFT JOIN LOGPEDIDOFV LOGFV WITH(NOLOCK) ON (LOGFV.NUMPEDIDOERP = CAB.NUMPEDIDO) 
    LEFT JOIN CABPEDVENDA_COMPLEMENTOS CABC WITH(NOLOCK) ON (CABC.NUMPEDIDO = CAB.NUMPEDIDO) 
    LEFT JOIN COBRANCA COB WITH(NOLOCK) ON CAB.CODCOBRANCA = COB.CODCOBRANCA 
    LEFT JOIN PESSOA TRANSP WITH(NOLOCK) ON CAB.CODTRANSPORTADORA = TRANSP.CODIGO 
        WHERE CAB.CODCLIENTE = CLI.CODIGO 
        AND V.CODIGO = CAB.CODVENDEDOR 
        AND NAT.CODIGO = CAB.CODNATOPERACAO 
        AND CID.CODMUNICIPIO = CLI.CODCIDADE 
        AND CLI.CODREGIAO = REG.CODIGO 
        AND CAB.STATUS IN (''L'',''P'',''B'',''C'',''F'') 
        AND CONVERT(CHAR(10), CAB.DTEMISSAO, 120 ) + '' '' + CONVERT(VARCHAR(8), CAB.DTEMISSAO, 108) BETWEEN @P0 AND @P1 
        AND CAB.CODEMPRESA = @P2 
        AND NOT (CAB.TIPOVENDA IN (''SAIDA_DAV'',''SAIDA_DAV_SR'') AND CAB.ISFATURADO = 1) 
       AND CAB.TIPOVENDA IN (''SAIDA_BALCAO'',''SAIDA_TELEMARKETING'',''ENTREGA_FUTURA'',''SAIDA_MANIFESTO'',''ORDEM_PRODUCAO'',''SAIDA_DAV'',''SAIDA_DEVOLUCAO'',''SAIDA_DAV_SR'') 
ORDER BY CAB.DTEMISSAO',N'@P0 nvarchar(4000),@P1 nvarchar(4000),@P2 int',N'2025-08-01 00:00:00',N'2025-08-01 23:59:59',1