exec sp_executesql N'SELECT I.CODPRODUTO, P.NOME AS PRODUTO, P.UNIDADE, ISNULL(I.QTPEDIDA,0) AS QTPEDIDA, ISNULL(I.QTENTREGUE,0) AS QTENTREGUE, ISNULL(I.QTRESTANTE,0) AS QTRESTANTE,  
ISNULL(I.VLUNITARIO,0) AS VLUNITARIO, ISNULL(I.VALORICMSST,0) AS VALORICMSST, ISNULL(I.VALORIPI,0) AS VALORIPI, ISNULL(I.PERDESCONTO,0) AS PERDESCONTO, 
ISNULL(I.VLDESCONTO,0) AS VLDESCONTO, ISNULL(I.VLFRETE,0) AS VLFRETE, ISNULL(I.VLSEGURO,0) AS VLSEGURO, ISNULL(I.VLOUTRASDESP,0) AS VLOUTRASDESP, ISNULL(I.SUBTOTAL,0) AS SUBTOTAL, 
ISNULL(I.VALORTOTENTREGUE,0) AS VALORTOTENTREGUE, ISNULL(I.VALORTOTRESTANTE,0) AS VALORTOTRESTANTE, ISNULL(I.VLVENDA,0) AS VLVENDA, ISNULL(I.TOTPESOBRUTO,0) AS TOTPESOBRUTO, 
ISNULL(I.TOTPESOLIQUIDO,0) AS TOTPESOLIQUIDO, I.ID, ISNULL(I.VLUNITARIOORIG,0) AS VLUNITARIOORIG, I.TIPODESCONTO, ISNULL(P.CODFABRICA,'''') AS CODFAB,  
ISNULL(I.VOLUMEITEM,0) AS VOLUMEITEM, ISNULL(PE.USAESTLOTE,0) AS USAESTLOTE, ISNULL(PE.QTDISPONIVEL, 0) AS QTDISPONIVEL, 
ISNULL(PE.CODGRUPOPISCOFINS,0) AS CODGRUPOPISCOFINS, ISNULL(PE.CODGRUPOIPI, 0) AS CODGRUPOIPI, ISNULL(PE.CODGRUPOICMS, 0) AS CODGRUPOICMS 
	FROM ITEMPEDVENDA I WITH (NOLOCK), PRODUTO P WITH (NOLOCK), PRECO_ESTOQUE PE, CABPEDVENDA C WITH (NOLOCK) 
	WHERE I.CODPRODUTO = P.CODIGO 
	AND P.CODIGO = PE.CODPRODUTO 
	AND PE.CODEMPRESA = C.CODEMPRESA 
	AND C.NUMPEDIDO = I.NUMPEDIDO 
	AND I.NUMPEDIDO = @P0',N'@P0 int',77137